export const POST_LIST_REQUEST = "POST_LIST_REQUEST";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAIL = "POST_LIST_FAIL";

export const FILTERED_POST_LIST_REQUEST = "FILTERED_POST_LIST_REQUEST";
export const FILTERED_POST_LIST_SUCCESS = "FILTERED_POST_LIST_SUCCESS";
export const FILTERED_POST_LIST_FAIL = "FILTERED_POST_LIST_FAIL";

export const POST_REQUEST = "POST_REQUEST";
export const POST_SUCCESS = "POST_SUCCESS";
export const POST_FAIL = "POST_FAIL";
